### ISSUE TITLE
CMatchPause::Pause

### ISSUE THREAD

**Issue by Brazzabro** [SmileYzn/MatchBot#144]
the server crashes if you pause it immediately after the start of the match via the !menu
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf2321316 in CMatchPause::Pause() () from /home/rehlds/CWserverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
[Current thread is 1 (Thread 0xf7bd7700 (LWP 1243794))]
#0  0xf2321316 in CMatchPause::Pause() () from /home/rehlds/CWserverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
#1  0xf2310dfb in ReGameDLL_CSGameRules_RestartRound(IHookChain<void>*) () from /home/rehlds/CWserverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
#2  0xf251d376 in CHalfLifeMultiplay::RestartRound() () from /home/rehlds/CWserverfiles/cstrike/dlls/cs.so
#3  0xf252150f in CHalfLifeMultiplay::Think_OrigFunc() () from /home/rehlds/CWserverfiles/cstrike/dlls/cs.so
#4  0xf251d28c in CHalfLifeMultiplay::Think() () from /home/rehlds/CWserverfiles/cstrike/dlls/cs.so
#5  0xf24e5a33 in StartFrame() () from /home/rehlds/CWserverfiles/cstrike/dlls/cs.so
#6  0xf2280862 in ?? ()
#7  0xf7909020 in ?? () from /home/rehlds/CWserverfiles/engine_i486.so
#8  0xf7536905 in SV_Frame() () from /home/rehlds/CWserverfiles/engine_i486.so
#9  0xf754f352 in _Host_Frame(float) () from /home/rehlds/CWserverfiles/engine_i486.so
#10 0xf754f64d in Host_Frame(float, int, int*) () from /home/rehlds/CWserverfiles/engine_i486.so
#11 0xf754b1ad in CEngine::Frame() () from /home/rehlds/CWserverfiles/engine_i486.so
#12 0xf754a890 in CDedicatedServerAPI::RunFrame() () from /home/rehlds/CWserverfiles/engine_i486.so
#13 0x08049fe9 in StartServer(char*) ()
#14 0xf74c0720 in __wrap_rmdir () from /home/rehlds/CWserverfiles/filesystem_stdio.so
#15 0x00000000 in ?? ()
No symbol table info available.
```

**Comment by SmileYzn** [comment]
What build you tested it?

Try latest action build :pray:

**Comment by Brazzabro** [comment]
there is an error on the 2024 Release, 
there is no error on the latest version of action build

**Comment by suhrobina** [comment]
I encountered the same issue
