### ISSUE TITLE
Bug report when finish vote teams

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#68]
Hi, today I want to post a bug that I have. 

I cant make game using choose captains. 

Sometimes when vote teams ends i got crash. 

I was using timer for get players ready. 

and this:

```
mb_team_pick_type "-1"
mb_team_pick_menu "ab"

```
i got this log debug.log:
```

CRASH: Tue May 30 20:51:57 UTC 2023
Start Line: ./hlds_linux -game cstrike -strictportbind +ip 0.0.0.0 -port 27015 +clientport 27005 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 10 -pingboost 3 -debug -dev -noipx +sv_lan 0 -nojoy -secure +sv_password pcw -pidfile hlds.563476.pid
[New LWP 563490]
[New LWP 563505]
[New LWP 563506]
[New LWP 563509]
[New LWP 563518]
[New LWP 563519]
[New LWP 563520]
[New LWP 563521]
[New LWP 563522]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike -strictportbind +ip 0.0.0.0 -port 27015 +clientport'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf7e6063b in std::_Rb_tree_increment (__x=0x6e616d75) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65
[Current thread is 1 (Thread 0xf7b0a700 (LWP 563490))]
#0  0xf7e6063b in std::_Rb_tree_increment (__x=0x6e616d75) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65
#1  0xf23c5cf9 in CMatchTask::Frame() () from /home/csserver/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
#2  0xf23c5d7d in DLL_POST_StartFrame() () from /home/csserver/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
#3  0xf2359ed8 in ?? ()
#4  0xf785e420 in ?? () from /home/csserver/serverfiles/engine_i486.so
#5  0xf747f248 in SV_Frame() () from /home/csserver/serverfiles/engine_i486.so
#6  0x000c5f8f in ?? ()
#7  0x1a03a328 in ?? ()
#8  0x28000000 in ?? ()
#9  0x41ba03a3 in ?? ()
#10 0xaecae1c4 in ?? ()
#11 0x4070a6fb in ?? ()
#12 0x00000000 in ?? ()
No locals.
From        To          Syms Read   Shared Object Library
0xf7ee1130  0xf7ee2304  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf7e53914  0xf7e99c78  Yes         ./libstdc++.so.6
0xf7d13190  0xf7dd3511  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7b3a0f0  0xf7c8c566  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf7ef5090  0xf7f11dd3  Yes (*)     /lib/ld-linux.so.2
0xf7b0de04  0xf7b1d490  Yes         ./libgcc_s.so.1
0xf742c820  0xf751dfb0  Yes (*)     /home/csserver/serverfiles/engine_i486.so
0xf73ee3d0  0xf73f20a4  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf73db5c0  0xf73e5d74  Yes (*)     ./libsteam_api.so
0xf73bc5b0  0xf73cc8b4  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf7391e00  0xf73ad838  Yes (*)     /home/csserver/serverfiles/filesystem_stdio.so
0xf50ee000  0xf68f3074  Yes (*)     /home/csserver/.steam/sdk32/steamclient.so
0xf27793a0  0xf27bca90  Yes (*)     /home/csserver/serverfiles/./cstrike/addons/metamod/metamod_i386.so
0xf2521ba0  0xf26b9b00  Yes (*)     /home/csserver/serverfiles/cstrike/dlls/cs.so
0xf2372490  0xf23c66d8  Yes (*)     /home/csserver/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
0xf0fc1530  0xf0ff09b4  Yes (*)     /home/csserver/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
0xeecfb000  0xf050f074  Yes (*)     ./steamclient.so
0xf2160670  0xf21d6020  Yes (*)     ./crashhandler.so
0xf233d300  0xf23438c4  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xf23351c0  0xf2337ea4  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xf231d3b0  0xf2329c64  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xffa3d030:
 eip = 0xf7e6063b in std::_Rb_tree_increment (/valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65); saved eip = 0xf23c5cf9
 called by frame at 0xffa3d070
 source language c++.
 Arglist at 0xffa3d028, args: __x=0x6e616d75
 Locals at 0xffa3d028, Previous frame's sp is 0xffa3d030
 Saved registers:
  ebp at 0xffa3d028, eip at 0xffa3d02c
End of crash report****
```

I was testing it with 9 steam virtual machines and me as 10 player. 

![23](https://github.com/SmileYzn/MatchBot/assets/74840575/351db5ff-2463-4492-a510-9dece0c858ce)

**Comment by SmileYzn** [comment]
@yuyiken 

Sorry for delay, did you can test it again? with new build from action build system?

From here
https://github.com/SmileYzn/MatchBot/actions/runs/5157795094

I try to add debug symbols to final plugin. Soo i think that debug.log can return more detailed info

Thanks for patience :pray:

**Comment by SmileYzn** [comment]
@yuyiken 
Trying to fix it here https://github.com/SmileYzn/MatchBot/actions/runs/5158155974

**Comment by yuyiken** [comment]
Hi @SmileYzn , 

Its okay, I understand if you have no time or just busy. 

I just tested last build and still got same issue.

And thank you for still working on it.

```
CRASH: Fri Jun  2 21:29:02 UTC 2023
Start Line: ./hlds_linux -game cstrike -strictportbind +ip 0.0.0.0 -port 27017 +clientport 27005 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 10 -pingboost 3 -debug -dev -noipx +sv_lan 0 -nojoy -secure +sv_password pcw -pidfile hlds.788182.pid
[New LWP 788196]
[New LWP 788222]
[New LWP 788223]
[New LWP 788225]
[New LWP 788228]
[New LWP 788229]
[New LWP 788230]
[New LWP 788231]
[New LWP 788232]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike -strictportbind +ip 0.0.0.0 -port 27017 +clientport'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf7e6e63b in std::_Rb_tree_increment (__x=0x6e616d75, __x@entry=0xa0b9830) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65
[Current thread is 1 (Thread 0xf7b18700 (LWP 788196))]
#0  0xf7e6e63b in std::_Rb_tree_increment (__x=0x6e616d75, __x@entry=0xa0b9830) at /valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65
#1  0xf23d47d9 in std::_Rb_tree_iterator::operator++ (this=<synthetic pointer>) at /usr/include/c++/4.8.2/bits/stl_tree.h:197
#2  CMatchTask::Frame (this=0xf23e4120 <gMatchTask>) at MatchTask.cpp:53
#3  0xf23d485d in DLL_POST_StartFrame () at MetaDLL.cpp:88
#4  0xf2368ed8 in ?? ()
#5  0xf786c420 in ?? () from /home/csserver/serverfiles/engine_i486.so
#6  0xf748d248 in SV_Frame() () from /home/csserver/serverfiles/engine_i486.so
#7  0x00105cc0 in ?? ()
#8  0x2a13784d in ?? ()
#9  0x26800000 in ?? ()
#10 0x41c509bc in ?? ()
#11 0xb8e37211 in ?? ()
#12 0x408d45a5 in ?? ()
#13 0x00000000 in ?? ()
No locals.
From        To          Syms Read   Shared Object Library
0xf7eef130  0xf7ef0304  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf7e61914  0xf7ea7c78  Yes         ./libstdc++.so.6
0xf7d21190  0xf7de1511  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7b480f0  0xf7c9a566  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf7f03090  0xf7f1fdd3  Yes (*)     /lib/ld-linux.so.2
0xf7b1be04  0xf7b2b490  Yes         ./libgcc_s.so.1
0xf743a820  0xf752bfb0  Yes (*)     /home/csserver/serverfiles/engine_i486.so
0xf73fc3d0  0xf74000a4  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf73e95c0  0xf73f3d74  Yes (*)     ./libsteam_api.so
0xf73ca5b0  0xf73da8b4  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf739fe00  0xf73bb838  Yes (*)     /home/csserver/serverfiles/filesystem_stdio.so
0xf50fc000  0xf6901074  Yes (*)     /home/csserver/.steam/sdk32/steamclient.so
0xf27873a0  0xf27caa90  Yes (*)     /home/csserver/serverfiles/./cstrike/addons/metamod/metamod_i386.so
0xf252fba0  0xf26c7b00  Yes (*)     /home/csserver/serverfiles/cstrike/dlls/cs.so
0xf2381510  0xf23d5168  Yes         /home/csserver/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
0xf0fcf530  0xf0ffe9b4  Yes (*)     /home/csserver/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
0xeed09000  0xf051d074  Yes (*)     ./steamclient.so
0xf2160670  0xf21d6020  Yes (*)     ./crashhandler.so
0xf234c300  0xf23528c4  Yes (*)     /lib/i386-linux-gnu/libnss_files.so.2
0xf23441c0  0xf2346ea4  Yes (*)     /lib/i386-linux-gnu/libnss_dns.so.2
0xf232c3b0  0xf2338c64  Yes (*)     /lib/i386-linux-gnu/libresolv.so.2
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xff9ad2b0:
 eip = 0xf7e6e63b in std::_Rb_tree_increment (/valve/build/targets/src/gcc-4.6.1/libstdc++-v3/src/tree.cc:65); saved eip = 0xf23d47d9
 called by frame at 0xff9ad2f0
 source language c++.
 Arglist at 0xff9ad2a8, args: __x=0x6e616d75, __x@entry=0xa0b9830
 Locals at 0xff9ad2a8, Previous frame's sp is 0xff9ad2b0
 Saved registers:
  ebp at 0xff9ad2a8, eip at 0xff9ad2ac
End of crash report
```

**Comment by SmileYzn** [comment]
Now i can more one problem.
The vote system delete task without check if is runing in loop. Causing that crash.

I will try it to fix again.

**Comment by SmileYzn** [comment]
@yuyiken

Try to see if it will fix at https://github.com/SmileYzn/MatchBot/actions/runs/5180761607
